automation/Extension/firefox/data/content.js

Revert "Remove webdriver HTML attribute from documentElement and navigator"

---

automation/DeployBrowsers/deploy_firefox.py
automation/Extension/firefox/index.js
automation/Extension/firefox/lib/http-instrument.js
automation/Extension/firefox/lib/loggingdb.js
automation/MPLogger.py

Adding logging to Firefox extension, along with some basic log messages.
Future work, which I'd like to save for a different PR:
-Adding logging to the content script: I'd rather not couple this enhancement to that one, though they are similar.
It isn't productive to write tests that test specific log messages - if you can think of a more robust way to automate the check that logging works let me know.

Extension logging

---

install-dev.sh
install.sh

Improved the installer a bit so that it's more suitable for scripting.

Installer improvements

---

.travis.yml
requirements.txt
setup.cfg
test/manual_test.py

Before this lands (assuming it gets approved), we'll also need https://github.com/citp/OpenWPM/pull/200 in, with a rebase.

Add and run flake8 in Travis

---

automation/TaskManager.py
automation/schema.sql
automation/utilities/db_utils.py
test/test_crawl.py

Fixes https://github.com/citp/OpenWPM/issues/192

Fix Issue 192; normalize CrawlHistory table to crawl_history, for consistency

---

requirements.txt
setup.cfg
test/conftest.py
test/expected.py
test/manual_test.py
test/openwpmtest.py
test/test_crawl.py
test/test_custom_function_command.py
test/test_env.py
test/test_extension.py
test/test_http_instrumentation.py
test/test_js_instrument.py
test/test_profile.py
test/test_simple_commands.py
test/test_storage_vectors.py
test/utilities.py

Also not-yet **_fully_** ready for review, but I think this Should Just Work (tm).

Add and run flake8-isort in Travis builds

---

automation/DataAggregator/LocalAggregator.py
automation/MPLogger.py
automation/utilities/build_cookie_table.py
setup.cfg
test/test_http_instrumentation.py
test/test_pages/post_request_ajax.html

This fixes all errors reported by flake so that the build pipeline might work again

Fix all pep8 errors in the branch

---

test/test_http_instrumentation.py

This fixes one more problem with checking json results

Fix one more problem with checking json results

---

README.md
install-mac-dev.sh

Also updated the Mac section in the readme.
Note: The python packages are now installed in a local virtualenv in order to increase reproducability of Mac OpenWPM environments.

Updated install-mac-dev.sh to install on recent versions of OSX and XCode

---

automation/SocketInterface.py
automation/utilities/platform_utils.py
install-mac-dev.sh
test/manual_test.py

Allows demo crawls and manual tests to be run on a Mac natively.
Fixes https://github.com/mozilla/OpenWPM/issues/284
Works around https://github.com/mozilla/OpenWPM/issues/278

Some Mac-related improvements

---

automation/DataAggregator/parquet_schema.py
automation/Extension/firefox/feature.js/loggingdb.js
automation/TaskManager.py

With these changes, S3Aggregation/parquet works again.
Fixes #286

Fix for issue 286 (S3Aggregation/parquet)

---

automation/SocketInterface.py
automation/utilities/platform_utils.py
test/manual_test.py

This fixes all flake8 errors in the current master branch, so the build on travis-ci should be back to normal.

Fix all flake8 errors

---

.travis.yml

Also try to test the Dockerfile in travis-ci

Also try to test the Dockerfile

---

automation/Extension/firefox/package-lock.json
automation/Extension/firefox/package.json

`js-yaml` has a security advisory for versions <3.13.1. This runs a full npm update on our dependencies.

Update npm packages

---

install-dev.sh
requirements-dev.txt

Fixes #236 by restoring install-dev.sh and requirements-dev.txt (some of my wip PRs depend on these files to exist so it'd be great to have them in place for now)

Restored a lean version of install-dev.sh

---

automation/Extension/firefox/feature.js/index.js
automation/Extension/firefox/src/manifest.json
automation/Extension/webext-instrumentation/src/background/javascript-instrument.ts

Only register the JS instrument content script if JS instrument is enabled

---

.travis.yml
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/Extension/webext-instrumentation/src/lib/http-post-parser.ts
automation/Extension/webext-instrumentation/src/lib/string-utils.ts

Restored a version of the webext-instrumentation for travis (originally dropped in 49078b3b219da4b847e775f7ab095f437639e66e)

Restored travis for webext-instrumentation

---

automation/Extension/firefox/content.js/index.js
automation/Extension/webext-instrumentation/src/background/javascript-instrument.ts

Reverts a2dce7a5d30cec72455639f40e4b93dbe6bc9315

Bugfix for broken build

---

Dockerfile
README.md
run-on-osx-via-docker.sh

Restore run-on-osx-via-docker.sh

---

automation/DataAggregator/S3Aggregator.py

This is @englehardt's patch that avoids uploading of the same files multiple time within each OpenWPM container / instance. 
(A future patch can optionally use the shared redis server if available to ensure that this enhancement spans across all containers / instances used in a crawl)

Add filename caching to S3 aggregator

---

automation/Extension/webext-instrumentation/README.md
automation/Extension/webext-instrumentation/package.json

Noticed some outdated information after publishing to npm

Updated webext instrumentation readme and metadata

---

automation/default_browser_params.json

Added "navigation_instrument" parameter to default_browser_params.json file

Update default_browser_params to include "navigation_instrument" 

---

automation/Extension/webext-instrumentation/src/lib/js-instruments.ts

GH-408: Refactor String.prototype.rsplit to be a local function

---

.deploy-to-dockerhub.sh
.travis.yml

Deploy to Dockerhub

---

automation/Extension/webext-instrumentation/src/lib/js-instruments.ts

This is a follow up to https://github.com/mozilla/OpenWPM/pull/409

Remove unused interface

---

automation/DataAggregator/S3Aggregator.py
crawler.py
test/test_s3_aggregator.py

Add timeout to batch upload in S3Aggregator

---

crawler.py
requirements.txt
test/openwpmtest.py

Activates Sentry in crawler.py if SENTRY_DSN env var is configured
Part of solution to #406

Activate Sentry in crawler.py

---

crawler.py

Forgot this in https://github.com/mozilla/OpenWPM/pull/457

Add JS_INSTRUMENT_MODULES to crawler.py

---

run-on-osx-via-docker.sh

As mentioned in https://github.com/mozilla/OpenWPM/issues/474
Edit: Removed "Fixed" keyword

Add --shm-size argument to docker osx helper script

---

automation/Extension/firefox/src/privileged/sockets/api.js
install-mac-dev.sh
install-system.sh

Fixes https://github.com/mozilla/OpenWPM/issues/454
Should probably not be merged before Firefox 69 is officially released.

Upgrade to fx69

---

demo.py

Add a little more context around parallelization in demo.py

---

automation/DataAggregator/S3Aggregator.py

Remove unsupported parameter for write_to_dataset

---

Dockerfile

Made the Dockerfile do the same steps as build-extension.sh
Hopefully closes #508

Use extension built within Dockerfile instead of from the local system

---

README.md

Make MacOS Docker GUI instructions easier to parse

---

automation/Extension/firefox/src/privileged/sockets/api.js

Using new ExtensionCommon.EventManager Constructor

---

automation/Extension/webext-instrumentation/package-lock.json
install-mac-dev.sh
install-system.sh

Closes #512 
Changes the Firefox version used to crawl to 70

Updated to FF70

---

crawler.py

Adding to the configuration that is configurable for crawls by env vars

More crawler configuration

---

test/test_pages/js_instrument/large_payloads.html

Created this for use in manual testing mode while developing the JESTr study add-on. Seems relevant to add to the general test page collection since there are several pages out there that use canvas heavily and the platform should handle it.

Add large payloads test page

---

test/test_mp_logger.py

This was needed as the old testcases were sending exc_text instead
while real runs crashed on exc_info formatting
Closes #534

Created a testcase that sends exc_info to MPLogger

---

automation/DataAggregator/S3Aggregator.py
automation/DataAggregator/parquet_schema.py
test/test_s3_aggregator.py

Generate positive visit_id and crawl_ids

---

automation/TaskManager.py

Fix missing command_status for critical errors

---

crawler.py

Setting site_rank in crawler.py

---

.gitignore
.travis.yml
README.md
automation/TaskManager.py
test/test_s3_aggregator.py

Type annotation and refactoring in TaskManager.py

---

automation/BrowserManager.py
automation/CommandSequence.py
automation/Commands/Commands.py
automation/Commands/command_executor.py
automation/TaskManager.py
test/test_extension.py

This a WIP PR. I have currently just added the base class and subclasses for the commands in the Commands.py file. Please let me know if this is the way you wanted it to be implemented(I have used factory method pattern) and if the naming of classes etc is ok. 
Also a few questions
1. Do we intend to pass the entire object to function calls for eg [here](https://github.com/mozilla/OpenWPM/blob/59e79a7adbb41b2a801b7f8fb9c2863cb6222cc7/automation/TaskManager.py#L457) or send something like obj.command
2. Also we are getting a visit_id [here](https://github.com/mozilla/OpenWPM/blob/59e79a7adbb41b2a801b7f8fb9c2863cb6222cc7/automation/TaskManager.py#L452) and also a visit_id [here](https://github.com/mozilla/OpenWPM/blob/master/automation/Commands/command_executor.py#L12). Which one am I …

Adding Commands.py file

---

automation/CommandSequence.py
automation/Commands/Types.py
automation/Commands/command_executor.py

@vringar I've made the changes for __repr__
The tests seem to have errored, is it possible for me to retrigger the build

Correcting return value of __repr__

---

automation/DataAggregator/parquet_schema.py
automation/DataAggregator/schema.sql
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/Extension/webext-instrumentation/src/schema.ts
test/test_http_instrumentation.py

Removed is_full_page and is_frame_load in http_requests as prescribed in  #565

removed iframe/page type check from HTTP requests

---

automation/Commands/profile_commands.py

Removing missed reference to flash cookies

---

crawler.py

Add CALLSTACK_INSTRUMENT environment variable

---

.travis.yml
README.md
automation/BrowserManager.py
automation/DeployBrowsers/deploy_firefox.py
automation/TaskManager.py
automation/default_browser_params.json
crawler.py
demo.py
install-system.sh
requirements-dev.txt
requirements.in
requirements.txt
test/openwpmtest.py
test/test_simple_commands.py

Restore xvfb

---

demo.py

This is a tiny tweak. I'm regularly messing with demo.py to try out various things. This small tweak just makes each time I do that a little quicker as I just have to add and delete lines rather than editing around the parens.

Tweak demo.py

---

requirements-dev.in
requirements-dev.txt

We describe usage of `pip-tools` notably `pip-compile` in our README, so we should include it in our dependencies

Added pip-tools as a dev requirement

---

automation/Commands/utils/webdriver_utils.py
test/test_webdriver_utils.py

Fixing neterror re

---

.codecov.yml
.travis.yml
environment.yaml
scripts/environment-unpinned-dev.yaml

Codecov added

---

automation/TaskManager.py

Asserting that unpickled exception is an exception

---

README.md

Update examples for JS instrument settings

---

.travis.yml
scripts/travis.sh
test/test_failure.py

Make CI error out if our tests aren't passing

---

automation/BrowserManager.py
automation/Commands/Types.py
automation/Commands/browser_commands.py
automation/Commands/command_executor.py
automation/Commands/profile_commands.py
automation/DataAggregator/BaseAggregator.py
automation/DataAggregator/LocalAggregator.py
automation/DataAggregator/S3Aggregator.py
automation/DataAggregator/parquet_schema.py
automation/DataAggregator/schema.sql
automation/DeployBrowsers/deploy_firefox.py
automation/DeployBrowsers/selenium_firefox.py
automation/Extension/firefox/feature.js/callstack-instrument.js
automation/Extension/firefox/feature.js/index.js
automation/Extension/firefox/feature.js/loggingdb.js
automation/Extension/webext-instrumentation/src/background/cookie-instrument.ts
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/Extension/webext-instrumentation/src/background/javascript-instrument.ts
automation/Extension/webext-instrumentation/src/background/navigation-instrument.ts
automation/Extension/webext-instrumentation/src/schema.ts
automation/TaskManager.py
automation/utilities/build_cookie_table.py
automation/utilities/platform_utils.py
test/test_callstack_instrument.py
test/test_custom_function_command.py

Renamed crawl_id to browser_id

---

automation/Extension/firefox/package-lock.json
automation/Extension/webext-instrumentation/package-lock.json
test/test_callback.py
test/test_s3_aggregator.py

to avoid https://github.com/mozilla/OpenWPM/issues/732
Please note that this doesn't close the issue.

Moved all s3 tests into one class

---

README.md
automation/BrowserManager.py
automation/DeployBrowsers/deploy_firefox.py
automation/default_browser_params.json
automation/utilities/platform_utils.py
test/test_profile.py

Introducing seed profile

---

automation/BrowserManager.py
automation/TaskManager.py
automation/utilities/multiprocess_utils.py

I managed to forget to pass a logger everywhere and we don't have any tests on this codepath

Hotfixing kill_process_and_children

---

automation/BrowserManager.py

Another tuple where we expected an exception

Fixed exception not bubbling correctly through the status_queue

---

automation/CommandSequence.py
automation/Commands/browser_commands.py
automation/Commands/command_executor.py
automation/Commands/types.py
demo.py

@vringar I spent a while trying to understand your code and here's what I came up with (it will certainly need revision)
It looks like for the other classes you created, i.e. `GetCommand` and `BrowseCommand`, the only variables to be printed by repr method were to be instantiated of the class. In the `SaveScreenShotCommand` , when running `demo.py` I did not see it called anywhere and hence, did not know how to which variables to instaitate.
This leads me to a major issue I encountered. After unsuccessfully attempting to debug the program, I read that you must build `./scripts/build-extension.sh` and then run `python -m test.manual_test`
I did this and the program stopped (according to the terminal) but I did not know how to advance it. 
I've got a working copy of the repo in VScode and …

Command refactoring

---

automation/CommandSequence.py
automation/Commands/browser_commands.py
automation/Commands/command_executor.py
demo.py

Revert "Command refactoring"

---

automation/TaskManager.py
scripts/prune-environment.py

Clean up un-context-managed use of open

---

automation/DataAggregator/parquet_schema.py
automation/DataAggregator/schema.sql
automation/Extension/webext-instrumentation/package-lock.json
automation/Extension/webext-instrumentation/src/background/dns-instrument.ts
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/Extension/webext-instrumentation/src/lib/response-body-listener.ts
automation/Extension/webext-instrumentation/src/schema.ts
automation/Extension/webext-instrumentation/src/types/browser-web-request-event-details.ts

Change request_id to integer

---

README.md

This updates the study count to the newest value, and updates the link to a new table maintained on Princeton's page.

Update study count with new milestone

---

docs/Schema-Documentation.md
openwpm/DataAggregator/parquet_schema.py
openwpm/DataAggregator/schema.sql
openwpm/TaskManager.py
test/test_timer.py

Adding performance timer to see how much time a command took

---

test/test_webdriver_utils.py

Removed unneccessary List unpacking

---

test/test_webdriver_utils.py

Fixes updated change issue in #800

Updated stored commands in test_webdriver_utils.py

---

crawler.py
demo.py

Resolving imports to avoid errors

---

openwpm/task_manager.py

Made taskmanager a context manager

---

docs/Configuration.md
package.json

Updated wording for profiles

---

openwpm/Extension/firefox/feature.js/loggingdb.js

This way the default config in index.js and the check in loggingdb.js
match up

Adjusted check for debug mode in loggingdb.js

---

.github/workflows/build-container.yaml

Restoring Docker build

---

openwpm/browser_manager.py
openwpm/commands/profile_commands.py
openwpm/utilities/multiprocess_utils.py
test/test_crawl.py
test/test_profile.py

This PR  updates some of the existing profile tests.

Update profile tests

---

package-lock.json
package.json

Added  "info": "npm-scripts-info" under scripts as described. so now the descriptions under scripts-info can be displayed.
Closes #870

Added npm script info under scripts

---

README.md

Link to RTD documentation from README 
issue code - #915

Added RTD link to Readme

---

.pre-commit-config.yaml
docs/environment-rtd.yaml
environment.yaml
openwpm/browser_manager.py
scripts/environment-unpinned-dev.yaml
test/conftest.py
test/openwpmtest.py
test/test_crawl.py
test/test_task_manager.py

Stop AssertionErrors crashing production crawls

---

CHANGELOG.md
Extension/firefox/README.md
Extension/firefox/package.json
Extension/webext-instrumentation/README.md
Extension/webext-instrumentation/src/lib/js-instruments.ts
README.md
crawler.py
docs/Configuration.md
docs/Release-Checklist.md
docs/Using_OpenWPM.md
install.sh
openwpm/config.py
openwpm/deploy_browsers/configure_firefox.py
openwpm/deploy_browsers/deploy_firefox.py
openwpm/storage/storage_controller.py
openwpm/storage/storage_providers.py
scripts/repin.sh
test/manual_test.py

Updating repo links + a few missed references from the previous PR.

Remove references to Mozilla

---

openwpm/config.py

chore: removed invalid resource type

---

Extension/README.md
scripts/build-extension.sh

changed npm install to npm ci when building the extension

---

.github/workflows/run-tests.yaml
demo.py

feat(ci): check that demo.py works

---

openwpm/storage/storage_controller.py

fix(storage_controller): fix race condition during shutdown
