automation/BrowserManager.py
automation/Commands/profile_commands.py
automation/DeployBrowsers/deploy_firefox.py
automation/Errors.py
automation/TaskManager.py
automation/default_browser_params.json
automation/default_manager_params.json
install.sh
test/test_profile.py

These changes should make profile handling more intuitive and stable under various crawl conditions. Profile errors are now treated as critical and will stop crawls (to avoid a crawl continuing after a profile fails to load correctly). Profiles should remain persistent through crashes, and profiles should always be written on shut down (through the new `profile_archive_dir` option).
Follow up bugfixes to come in #40.

Fix several profile bugs and add tests

---

.travis.yml
README.md
automation/DataAggregator/LevelDBAggregator.py
automation/Proxy/mitm_commands.py
automation/platform_utils.py
install.sh
requirements.txt
test/test_env.py

This PR adds .travis.yml file to run continuous integration tests on Travis.
Install pytest for Travis tests.
Move python dependencies to requirements.txt to make it compatible with Travis.
Use mmh3 instead of pyhash.
pyhash cannot be installed on Travis due to an outdated check for
libboost_python.so. mmh3 has the same functionality and it's better
maintained.

Run continuous integration tests using Travis

---

automation/Commands/browser_commands.py

Without this, it's possible that the homepage isn't given enough time to load and no links are found.

Wait for homepage to load after back before looking up links

---

automation/Extension/firefox/data/content.js

Fixes #91.
The fix assumes that OpenWPM's `content.js` runs _after_  Selenium code linked below.
- https://github.com/SeleniumHQ/selenium/blob/b82512999938d41f6765ce8017284dcabe437d4c/javascript/firefox-driver/extension/content/server.js#L49
- https://github.com/SeleniumHQ/selenium/blob/b82512999938d41f6765ce8017284dcabe437d4c/javascript/firefox-driver/extension/content/dommessenger.js#L98
Manually tested on https://output.jsbin.com/webawamabu.
The console logs should read:
```
- Successfully started all instrumentation
- navigator.webdriver:  undefined
- webdriver in navigator:  false
- documentElement attribute webdriver:  null
```

Remove webdriver HTML attribute from documentElement and navigator

---

test/expected.py
test/test_http_instrumentation.py
test/test_pages/http_stacktrace.html

The test_http_instrumentation.py test was passing without even running the asserts due to a typo on the URL.
DRY in the expected.py.
Fix tab-space mix up in the test page.

Fix test page URL and asserts in the HTTP stacktrace test.

---

automation/Extension/firefox/lib/loggingdb.js

When visit_id is null, and the extension attempts to log something, it should send '-1' instead of null to the data aggregator.

Make visit_id = -1 when visit_id would otherwise be null

---

automation/utilities/build_cookie_table.py

Fall back to proxy based tables if extension based http_requests
or http_responses does not exist.

Use extension based http request and responses for building cookie tables

---

automation/DataAggregator/DataAggregator.py

Sometimes a query fails with "database is locked". By changing the timeout from the default value of 5 seconds to 60 seconds, we can maybe avoid that problem. The problem usually looks like this in the logs:
```
DataAggregator       - ERROR    - Unsupported query
<class 'sqlite3.OperationalError'>
database is locked
```

Change sqlite timeout to 60 seconds to avoid database locking problems.

---

install.sh

Some editions of ubuntu 16.04 such as the default docker images do not come with curl and wget. So just try to install them in install.sh. When they are already installed, they will maybe be updated but it is not supposed to cause any problems.

Install curl and wget in the installer.

---

requirements.txt

IPython 6.0 and newer versions do not support python 2.7 anymore. For python 2.7 and older versions, there is still IPython 5.x. When using the default version of pip (8.1.1) in Ubuntu 16.04, the following problem might be encountered when running 'pip install -U -r requirements.txt':
```
IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Beginning with IPython 6.0, Python 3.3 and above is required.
See IPython `README.rst` file for more information:
https://github.com/ipython/ipython/blob/master/README.rst
Python sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0) detected.
```
When using the installer with 'install.sh', then this problem is not encountered since pip is …

Use IPython < 6.0 for python 2.7.

---

automation/BrowserManager.py
automation/DeployBrowsers/deploy_firefox.py

The XVFB command format must have changed at some point, causing our
simple index-based parsing of the display port to fail. This bugfix
updates to the new command format by assuming the port is the last item
in the list.

Bugfix: display port parsing was incorrect, causing lockfiles to accumulate in /tmp

---

automation/TaskManager.py

Faulty comparison (first with integers, and only after that with '\*' and '\*\*') made the code crash when execute_command_sequence was called with the special '\*' and '\*\*' values. This made the demo.py disfunctional. The order was changed to make the special values work again.

Fix of browser sync/index in _distribute_command

---

automation/DataAggregator/DataAggregator.py
automation/DataAggregator/LevelDBAggregator.py
automation/MPLogger.py
automation/SocketInterface.py

By giving the thread that accepts the socket connections in socketserver a name, the code should be easier to debug so that in case an exception happens, it is clear in which thread it happened.
This will not fix issue #145 but it will help at least to debug it.

Give the thread for socketserver a name.

---

test/expected.py
test/manual_test.py
test/test_crawl.py
test/test_custom_function_command.py
test/test_extension.py
test/test_profile.py
test/test_simple_commands.py
test/test_storage_vectors.py

This patch addresses all ```flake8``` issues (in the test/ dir) except for E501, so helps with https://github.com/citp/OpenWPM/issues/116 (but doesn't obviate further fixes).  And, if accepted, we'll need it *before* we merge in https://github.com/citp/OpenWPM/pull/199.
```
./test_profile.py:23:68: E231 missing whitespace after ','
./test_profile.py:23:80: E501 line too long (86 > 79 characters)
./test_profile.py:30:46: E261 at least two spaces before inline comment
./test_profile.py:31:39: E261 at least two spaces before inline comment
./test_profile.py:32:39: E261 at least two spaces before inline comment
./test_profile.py:39:46: E261 at least two spaces before inline comment
./test_profile.py:40:39: E261 at least two spaces before inline comment
./test_profile.py:41:39: E261 at least …
```

Fix all flake8 issues except for E501

---

README.md

Rename `document_url` to `doc_url` in the README.

---

automation/BrowserManager.py
automation/DataAggregator/LocalAggregator.py
automation/DataAggregator/S3Aggregator.py
automation/DeployBrowsers/selenium_firefox.py
automation/Errors.py
automation/MPLogger.py
automation/SocketInterface.py
automation/utilities/Cookie.py
setup.cfg
test/test_http_instrumentation.py
test/utilities.py

Running autopep8 on a clean branch which has no other pep8 errors. This should allow for cleaner diffs if someone decides to use autopep8 for a future PR.
Also note that I updated the isort config with some additional context.

Run autopep8 to fix errors not flagged by flake8

---

automation/DataAggregator/LocalAggregator.py
automation/DataAggregator/S3Aggregator.py
automation/Extension/firefox/feature.js/loggingdb.js
test/test_http_instrumentation.py

The response body might contain binary content that cannot be correctly represented by a string. This patch assumes that the openwpm-webext-instrumentation returns the response body as an Uint8Array instead of a string. It is then encoded using base64 to make it string-safe and then send to the DataAggregator of OpenWPM to be saved in a database there.
This patch needs a change in openwpm-webext-instrumentation which is currently not available in the official repository. As long as mozilla/openwpm-webext-instrumentation#45 has not been merged, the patch will not work correctly.

Use base64 encoding for the response body

---

automation/SocketInterface.py

This exception is not defined in 2.7. From my testing, there doesn't seem to be an alternate exception thrown on MacOS so the best option seems to be to define a dummy exception.

Fix PEP8 Errors on python2 caused by ConnectionAbortedError

---

automation/DataAggregator/parquet_schema.py
automation/schema.sql
test/test_http_instrumentation.py

A recent version of openwpm-webext-instrumentation also supports HTTP
POST request in which the POST body is only available as raw binary
data that is stored in the post_body_raw column.
This change updates the database structure with that column and adjusts
the tests so that those cases are correctly tested.
Before this can be merged, https://github.com/mozilla/openwpm-webext-instrumentation/pull/47 needs to be merged.

Handle HTTP POST requests with raw form data

---

test/test_http_instrumentation.py
test/test_pages/post_request_ajax.html

This is an updated PR for https://github.com/mozilla/OpenWPM/pull/311
In a nutshell, the code in the previous PR was correct, but the post body was considered to be "raw" by Firefox, so it only works when https://github.com/mozilla/OpenWPM/pull/315 has been merged.
This PR includes https://github.com/mozilla/OpenWPM/pull/315, otherwise it would not work.

Mozilla rmjquery raw post

---

test/test_storage_vectors.py

Previously, test_js_profile_cookies used _dump_profile_cookies_ which dumps the Firefox internal SQLite database to a table. This doesn't work very well anymore in the current version of Firefox and OpenWPM. Instead, the new extension provides a _javascript_cookies_ table that is filled with the cookies when _cookie_instrument_ is set to true. This commit updates the test so that the new table is used now and checks whether a cookie set by JavaScript is correctly recorded there.

Fix test_js_profile_cookies

---

README.md
automation/CommandSequence.py
automation/Commands/browser_commands.py
automation/Commands/command_executor.py
automation/Commands/utils/firefox_profile.py
automation/DataAggregator/parquet_schema.py
automation/schema.sql
demo.py
test/test_storage_vectors.py

This command is no longer necessary with the new instrumentation. It was
broken by the latest Firefox upgrade, so it no longer makes sense to
keep it around.

Remove dump_profile_cookies command.

---

test/test_http_instrumentation.py

Firefox is currently not able to return the FormData with the file contents, currently only the filenames are returned. This is due to a limitation in the current API implementation. Therefore, this commit disables the file upload test.

Disable file upload test

---

.dockerignore
.gitignore

Somewhat synchronized with gitignore but dedicated to ignoring the largest files and directories that may be lying around in a developer's openwpm folder.
Before (on my machine):
Sending build context to Docker daemon  1.715GB
After:
Sending build context to Docker daemon  71.97MB

Add .dockerignore

---

demo.py

Just to make sure that newcomers don't get the impression that OpenWPM only does HTTP and Cookies :)
Enabling JS instrument also works around https://github.com/mozilla/OpenWPM/issues/289

Enable navigation and js instruments for demo crawl

---

build-extension.sh

Before looking into the script, I was unsure that the openwpi.xpi actually got replaced by the freshly built xpi (mentioned last in the current output: `Your web extension is ready: dist/openwpm-1.0.zip`). This clarifies that.

Print the result of the build extension script when it has finished

---

automation/Extension/firefox/content.js/index.js
automation/Extension/firefox/feature.js/index.js
automation/Extension/webext-instrumentation/src/background/javascript-instrument.ts

Fixes #376
Related: https://github.com/mozilla/OpenWPM/pull/291#issue-273586535
Also paves way for https://github.com/mozilla/OpenWPM/issues/353 by providing a method of passing config options without editing the content script.
Note: This PR includes the commit from #375, so to keep clean PRs, that PR should be merged first, followed by this being rebased on the subsequent master.

Pass config['testing'] testing flag to content scripts

---

README.md
automation/BrowserManager.py
automation/CommandSequence.py
automation/Commands/browser_commands.py
automation/Commands/profile_commands.py
automation/TaskManager.py
demo.py
test/test_crawl.py
test/test_profile.py

Profile saving has long had intermittent issues. The update to Firefox 68 has fully broken profile saving. I've created [a project](https://github.com/mozilla/OpenWPM/projects/2) to track these issues, have added exceptions to OpenWPM for codepaths that rely on a browser profile (stateful crawling and profile dumping), and have disabled the profile tests.

Disable profile saving

---

install-system.sh

Using the "latest" taskcluster build url means that OpenWPM will automatically update to the newest build as soon as it's released. This is great for keeping things up to date, but not so great when there are breaking changes between major releases. Unfortunately there is no way to specify "give me the latest point release of Firefox XX", so we will hardcode specific builds for the time being. See #381 for a discussion of our options.

Hardcode FF binary

---

automation/DataAggregator/BaseAggregator.py
automation/DataAggregator/S3Aggregator.py
test/openwpmtest.py
test/test_pages/s3_aggregator.html
test/test_s3_aggregator.py

Will fix #277. Alternative to https://github.com/mozilla/OpenWPM/pull/323, which has errors related to signed/unsigned integers and does not pass the new included test. I verified that the master branch fails this test due to the truncation issue.
This also fixes two other issues:
* The S3 Aggregator would silently drop the last page visit (or set of visits).
* `utilities::get_test_config` accepts a browser count as an argument, but only makes the first browser headless.

Fix visit_id range for JS limits.

---

automation/DeployBrowsers/deploy_firefox.py
demo.py

We know MacOS will throw XVFB errors when we attempt to start a virtual display using `pyvirtualdisplay`. Rather than relying on a user to skip the `headless` configuration, we prevent OpenWPM from initializing the display on darwin even when the config parameter is set.
@nhnt11 or @motin: do you mind to test this on MacOS?

Disable virtual display creation for MacOS

---

automation/Extension/webext-instrumentation/.publishrc

Required since scoped npm packages are attempted to be published as private by default.
Blocks https://github.com/mozilla/OpenWPM/issues/329

Set @openwpm/webext-instrumentation package to be published as a public package

---

install-mac-dev.sh
install-system.sh

In https://github.com/mozilla/OpenWPM/pull/385 we hard-coded the unbranded version of Firefox to a specific build. 
This PR makes this available also for the Mac build, and changes the build to correspond to the one that matches Firefox 68 (according to https://wiki.mozilla.org/Add-ons/Extension_Signing#Unbranded_Builds where this is tracked)

Use the Unbranded build that corresponds to Firefox 68 release (for both Linux and Mac)

---

automation/DataAggregator/S3Aggregator.py
crawler.py
test/test_s3_aggregator.py
test/utilities.py

This moves the config files on S3 into a subdirectory. Since there are typically hundreds of files, this will keep the root directory much cleaner.

Move config files into subdirectory

---

crawler.py

Allows for use of Google Cloud Memorystore for Redis in GCP for instance, as implemented in https://github.com/mozilla/openwpm-crawler/pull/20

Configurable Redis host

---

.travis.yml
automation/Commands/utils/XPathUtil.py
automation/TaskManager.py
automation/utilities/platform_utils.py
requirements-dev.txt
setup.cfg
test/test_extension.py

Broken out from #438.
Localstack released 10.X on August 3rd. The newest version has installation issues. See #439. Pinning to `0.9.6` then introduced a bunch of `flake8` errors that we didn't have before. This is caused by the fact that localstack includes `flake8-quotes` as a dependency (https://travis-ci.org/mozilla/OpenWPM/jobs/568044495#L2129-L2130) and this plugin flags any use of double quotes as an error. Unfortunately flake8 automatically loads any installed plugins and doesn't provide a way to disable an installed plugin or restrict the set of possible plugins (https://gitlab.com/pycqa/flake8/issues/133). Thus, I've decided to disable the entire `QXXX` error code range, which as of 2 years ago isn't used by any plugins we plan to install …

Pin localstack to older version to fix dependency issues

---

automation/DataAggregator/S3Aggregator.py

Will rebase once #434 is merged into master. See the commit message for https://github.com/mozilla/OpenWPM/commit/4a0e4e4ede9120c28cabe2c35fef0487f9835220 for a description of the issue.
This should fix errors of this type: https://sentry.prod.mozaws.net/operations/web-crawls/issues/6111973/, which are likely lead to the socket errors we're seeing here: https://sentry.prod.mozaws.net/operations/web-crawls/issues/6101037/.

Fix S3Aggregator crash when records are flushed twice

---

automation/BrowserManager.py
automation/Commands/browser_commands.py
automation/DataAggregator/BaseAggregator.py
automation/DataAggregator/S3Aggregator.py
automation/MPLogger.py
test/test_mp_logger.py

This is addressing some of the errors observed in a recent large crawl.

Improved stability and error logging

---

automation/Extension/firefox/feature.js/loggingdb.js

Allows for easier-on-the-eye inspection from the devtools console.

Extension debug console output sent without stringification

---

demo.py

I believe this makes the behavior of demo.py somewhat easier to understand, and reflects the most common use case for multiple browsers (simple parallelization).
Ideally, we should have an examples-directory to demonstrate more advanced use cases, so that the demo.py can stay simple.

Avoid using "index='**'" in demo.py since it is a bit confusing

---

automation/Extension/webext-instrumentation/src/lib/js-instruments.ts

... for also logging access (gets) to instrumented function properties, not only their execution (calls).

Add logSettings.logFunctionGets

---

automation/Extension/firefox/content.js/index.js
automation/Extension/firefox/feature.js/index.js
automation/Extension/webext-instrumentation/src/background/javascript-instrument.ts
automation/Extension/webext-instrumentation/src/content/javascript-instrument-content-scope.ts
automation/Extension/webext-instrumentation/src/content/javascript-instrument-page-scope.ts
automation/default_browser_params.json

... with default value "fingerprinting" for instrumenting fingerprinting-related apis.
This is a step towards https://github.com/mozilla/OpenWPM/issues/353, allowing custom instrumentation to be implemented without having to comment out the fingerprinting-related api:s, which breaks many of the tests.

Add config option js_instrument_modules

---

README.md
automation/DataAggregator/LocalAggregator.py
automation/DeployBrowsers/deploy_firefox.py
automation/Extension/firefox/feature.js/index.js
automation/Extension/webext-instrumentation/package-lock.json
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/default_browser_params.json
automation/utilities/db_utils.py
crawler.py
test/test_http_instrumentation.py
test/test_profile.py

Fixes #344  
Possible ways to specify "save_content": 
* script,main_frame,sub_frame
* True
* False
But not:
* ['script', 'main_frame', 'sub_frame']
* '0'
* '1'

Allow content saving to be configured by any resource type

---

automation/Extension/webext-instrumentation/src/lib/js-instruments.ts

Restore the original prototype and constructor so that instrumented classes remain intact.
Fixes #461
This PR currently also includes https://github.com/mozilla/OpenWPM/pull/458, will be rebased after its merge.

Js instrument retain prototype and constructor

---

automation/MPLogger.py
automation/TaskManager.py
crawler.py
demo.py

This allows the log levels for the various outputs (console, file, and sentry) to be configured individually. It also includes a helper function to read log levels from env variables, as set by the complementary PR https://github.com/mozilla/openwpm-crawler/pull/25.
This also includes a small cleanup related to the `process_watchdog` feature, which is currently broken (see #174).

Configurable log levels

---

automation/BrowserManager.py
automation/Commands/browser_commands.py
automation/Commands/utils/webdriver_utils.py
automation/DataAggregator/parquet_schema.py
automation/MPLogger.py
automation/TaskManager.py
automation/schema.sql
automation/utilities/db_utils.py
test/manual_test.py
test/test_crawl.py

This contains the changes in #468, will rebase once that merges.
This PR includes several improvements to error logging:
1. `bool_success` has been removed from the `crawl_history` table and replaced by `command_status`, which is a string.
1. Successful commands use `"ok"`
2. Exceptions in the browser manager process use `"error"`
3. `about:neterror` WebDriverExceptions are special cased, and use `"neterror"`
4. Timeouts use `"timeout"`
2. Error messages and full, serialized tracebacks are included in the `crawl_history` table in the columns `error` and `traceback`. The error message for `about:neterror` exceptions parses out the exact error from the `about:` url -- e.g., `dnsError`.
3. `about:neterror` exceptions now log at the `logging.INFO` level, so they should not be included in …

Improved browser error logging in crawl_history

---

README.md

See https://github.com/mozilla/OpenWPM/issues/255#issuecomment-523762666 for a description of the problem. We can also consider moving over to `docker-compose` and hard coding this parameter there as described here: https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container, but I've chosen to take the simpler approach for now.

Add shared memory param to docker README

---

automation/Extension/webext-instrumentation/package.json
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
test/test_http_instrumentation.py

I call this work-in-progress because I'm not sure this is exactly what we want for Issue #245, although if it is, this might be close to a working fix.
Contrary to what is mentioned in #245 I didn't need to switch the listener to onBeforeRequest, since frameAncestors are also available in the onBeforeSendHeaders details object. 
I borrowed heavily from the work on this issue in privacy badger, only stripped their solution down to what I think we need for our purpose. I'm not entirely sure the four cases in my function cover all possible types of requests, but they are the ones I could identify through spec research and experiments.
This currently gives the entire URL for a given document, not only the host. That is especially true for service workers, where the returned URL might not …

Top-Level-Url attribution for HTTP-Requests

---

test/test_http_instrumentation.py
test/test_pages/http_service_worker_page.html
test/test_pages/http_worker_page.html
test/test_pages/shared/service_worker.js
test/test_pages/shared/worker.js

This patch adds a new testcase for the http instrumentation. 
A page is loaded that includes a worker script. The page and the script both load the same image, resulting in different requests with differen top-level-urls. 
As mentioned [here](https://github.com/mozilla/OpenWPM/pull/469#discussion_r321275524), I'm not sure this behaviour is actually desired. The request made by the script would have been attributed to the page's URL before [PR#469](https://github.com/mozilla/OpenWPM/pull/469), now it gets the URL of the script itself. The URL-attribution code might need to be adapted to handle requests by worker scripts differently.
Also, as mentioned, I wasn't able to create a similar test for a page with a Service Worker because that would reuqire the page to be served over https.

Add page visit test including a worker script making a request

---

requirements-dev.txt
requirements.txt
test/test_env.py

The S3Aggregator tests are failing again, but we didn't make any recent changes. I suspect this is due to `localstack` dependency issues, though I'm unable to reproduce the failures locally. Let's try removing the pin to an old version.

Update localstack to newest version

---

README.md

Removed it under "Running Measurements from inside the Container" as the instruction wasn't working anymore.
Closes #513

Removed one mention of python2 in README.md

---

.gitignore

Seeing as `.idea` was already there it only seemed okay

added .vscode to .gitignore

---

test/manual_test.py

This is necessary because Python3 differentiates between a bunch of bytes
,which is what we are getting from stdin, and a string

converting bytes to string in manual_test

---

README.md
requirements-dev.txt
requirements.txt

We should never operate directly on the compiled `.txt` files and should only make changes to the `.in` files. The current documentation is incorrect.
This also runs an update on both dependency files (using the correct commands).

Correct dependency management documentation

---

automation/Extension/webext-instrumentation/src/lib/js-instruments.ts

Found this error during manual testing. Introduced in #452. Happens when attempting to instrument a non-existing property without using the nonExistingPropertiesToInstrument config attribute.

Avoid TypeError: logSettings.nonExistingPropertiesToInstrument is undefined

---

install-mac-dev.sh
install-system.sh

Changing the download link to display the hash of the source it was build from.
This allows us to look up a tagged version in [hg](https://hg.mozilla.org/releases/mozilla-release/tags) (e.g. release or beta), take it's hash, paste it in and start working with it.
Closes #553

Better download links

---

install-dev.sh
install-pip-and-packages.sh

This PR resolves #577 by removing the `--user` flag from `pip3 install` and `python3 get-pip.py` commands.
This flag caused `install.sh` and `install-dev.sh` to fail with the following error when run in a virtual environment: `ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
As @englehardt [pointed out](https://github.com/mozilla/OpenWPM/issues/577#issuecomment-598475227), pip now behaves by default as if the `--user` flag was used when running outside of a virtual environment and there is no write permission for the global site-packages directory. Given that, using this flag is no longer necessary.

Remove --user flag from pip install

---

install-dev.sh

This PR adds `libsasl2-dev` to the development dependencies to prevent the following:
After the dependencies were updated in https://github.com/mozilla/OpenWPM/pull/581, running `install-dev.sh` would fail because the wheel for `sasl` couldn't be built:
```
In file included from sasl/saslwrapper.cpp:254:0:
sasl/saslwrapper.h:22:10: fatal error: sasl/sasl.h: No such file or directory
#include <sasl/sasl.h>
^~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for sasl
```

Add libsasl2-dev to development dependencies

---

automation/DeployBrowsers/selenium_firefox.py

We don't need to read the logfile, so we should just use "a".
Also somehow I get a "File is not seekable" exception on Python3.8.1 and this fixes it

Fixed log reading in python3.8.1

---

test/test_mp_logger.py

Fixes #559. We should be sure to file an issue to investigate, but for now we need to disable this test as it's failing constantly and makes it harder to read unrelated test failures.

Disable intermittent mp_logger test failure

---

automation/TaskManager.py
test/pytest.ini

I've seen these two warnings when running the tests for a while now:
1. https://travis-ci.org/github/mozilla/OpenWPM/jobs/671679677#L2939
2. https://travis-ci.org/github/mozilla/OpenWPM/jobs/671679677#L2948
Regarding the first warning, when `pytest.mark.slow` was added, it was perhaps assumed that it is one of the built-in marks of pytest, when it is in fact a custom mark. Registering it in the `pytest.ini` file, as mentioned in the [pytest documentation](https://docs.pytest.org/en/latest/mark.html#registering-marks) fixes the `PytestUnknownMarkWarning`. 
To address the second warning (`DeprecationWarning`), I just changed the deprecated `warn` method to `warning`.

Fix some test warnings

---

automation/TaskManager.py
setup.cfg

This PR fixes https://github.com/mozilla/OpenWPM/issues/501 by making the `_manager_watchdog` method in the `TaskManager` monitor the memory consumption of the Firefox process and all its child processes instead of that of the geckodriver process.

Restore intended functionality of memory watchdog

---

automation/TaskManager.py

This PR resolves https://github.com/mozilla/OpenWPM/issues/626 by checking if the geckodriver process has children before attempting to access its Firefox child process in the memory watchdog.

Prevent IndexError in memory watchdog

---

requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt

When looking at our dependencies I noticed that we had a lot of stuff in requirements.in that didn't belong there as it's strictly for developers.
So I moved it over and regenerated both `requirements.txt` as well as `requirements-dev.txt`

Moved developement tools into requirements-dev.in

---

automation/DataAggregator/parquet_schema.py
automation/DataAggregator/schema.sql
automation/Extension/webext-instrumentation/src/background/http-instrument.ts
automation/Extension/webext-instrumentation/src/schema.ts
test/test_http_instrumentation.py

Currently, the HTTP response headers of the server are not logged when
the server responds with an HTTP redirect. Wit this patch, they are
saved as well.
I can add a test for this as well, but when I would test for the exact headers present, then it might break easily once the HTTP server for the tests is upgraded.

Save the HTTP response headers for HTTP redirects

---

scripts/install-miniconda.sh

As conda have changed there url for `Miniconda3-latest-Linux-x86_64.sh` I've changed this to avoid at least one redirect and currently assured the future, in they disable the old url... which probably isn't soon, but why not do it right up :)

New url for conda

---

automation/TaskManager.py

Now the repr of all non trivial types will be stored in the JSON.  
This now allows RunCustomFunctionCommand to be serialized instead of crashing the issue_command thread.  
Closes #692

Fixing crawl_history for RunCustomFunctionCommand

---

CHANGELOG
README.md
automation/Extension/firefox/package-lock.json
automation/Extension/firefox/package.json
automation/Extension/webext-instrumentation/package-lock.json
automation/Extension/webext-instrumentation/package.json
environment.yaml
install.sh
scripts/environment-unpinned-dev.yaml
scripts/environment-unpinned.yaml
scripts/install-firefox.sh
scripts/repin.sh

I followed the steps in the new [release checklist](https://github.com/mozilla/OpenWPM/wiki/Release-Checklist) for this.

v0.10.0 / Firefox 77.0.1 release

---

automation/DataAggregator/LocalAggregator.py
automation/TaskManager.py
crawler.py

Removed noisy errors and deprecation warnings.
Closes #672

Better crawling experience

---

automation/Extension/webext-instrumentation/package-lock.json
automation/Extension/webext-instrumentation/src/lib/response-body-listener.ts
automation/Extension/webext-instrumentation/src/lib/sha256.ts

This code change updates the sha256 function to match the latest code on MDN.
It's my attempt to fix #711. 
I don't think we could say we definitively know it's worked to fix #711 without running it with a large crawl and repeating the analysis I did.
That said, we have tests in `test_http_instrumentation.py` that explicitly test for expected hashes. 
This code is simpler than the previous code. So if we think the tests are sufficient, then we could merge this on the grounds it's simpler and have an outstanding todo to rerun an analysis when a crawl's been run with this fix in.

Update hash function - use await (and generally clean up)

---

automation/TaskManager.py

We're getting a tuple instead of just the exception in python 3 so we need to unpack the tuple.
To test this code merge https://github.com/mozilla/OpenWPM/pull/735 and then comment out 
https://github.com/mozilla/OpenWPM/blob/dc9e02bdf2400f42754fa2876a16ff4a7cabd33f/test/test_profile.py#L106
This will trigger an assertion error in the BrowserManager, which will bubble into the TaskManager were the changed code will expose the desired behaviour.
While I see the necessity to test this code path I haven't attached any tests.
Closes #547

Fixed CriticalChildException in TaskManager.py

---

automation/utilities/platform_utils.py

This moves the js instrumentation config to a separate line so it doesn't create a huge and unreadable table. While we'd like to find a better way to output this information in the future, this removes the unnecessary messiness until then.
Closes #733.

Separate JS instrument config from table

---

test/test_s3_aggregator.py

This way we can get CI passing again.
Closes #755

Disabled s3 tests

---

automation/TaskManager.py
automation/default_manager_params.json
demo.py
docs/Configuration.md
docs/Platform-Architecture.md

Making memory_watchdog not run by default

---

test/manual_test.py

Minor fix for import no longer found. Quick question--given the recent work converting module names to abide by snake_case, should BrowserParams be browser_params?

Fixing import in manual_test.py broken after #807

---

docs/Configuration.md
openwpm/config.py
openwpm/task_manager.py
test/test_profile.py
test/test_task_manager.py

This PR will close #851. 
It does mainly two things:
1. Moves setting the default value of the `failure_limit` config option from the `TaskManager` to `config.py`
2. Corrects the behavior of `failure_limit` by reseting `failure_count` to 0 after every successfully completed command sequence instead of after every successful command.

Fix behavior of failure_limit

---

environment.yaml
openwpm/Extension/firefox/package-lock.json
openwpm/Extension/webext-instrumentation/package-lock.json
openwpm/commands/browser_commands.py

`webdriver.switch_to.alert` unlike most other variants of the `switch_to` API is not a function but a property.
This led to `TypeError:'Alert' object is not callable` when there was actually an `Alert` to switch to.
This PR fixes that behaviour.

Hotfixed GetCommand

---

demo.py
docs/Configuration.md
docs/Release-Checklist.md
openwpm/browser_manager.py
openwpm/command_sequence.py
openwpm/commands/profile_commands.py
openwpm/config.py
openwpm/deploy_browsers/configure_firefox.py
openwpm/deploy_browsers/deploy_firefox.py
openwpm/deploy_browsers/selenium_firefox.py
openwpm/task_manager.py
test/conftest.py
test/manual_test.py
test/test_callback.py
test/test_crawl.py
test/test_profile.py

This PR restores support for stateful crawling by addressing the core issue that broke it, i.e., the fact that geckodriver would delete the browser profile when closing or crashing before we had a chance to archive it. It does so by using a [custom profile](https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html) instead of creating the profile via the `FirefoxProfile` Selenium class. The custom profile is set via the arguments of the `Options` class. 
**Note:**
Geckodriver has a bug that makes it write the browser preferences we set, as well as its own default browser preferences, to a `user.js` file in the wrong profile directory when using a custom profile: https://github.com/mozilla/geckodriver/issues/1844. As a temporary workaround until this issue gets fixed, …

Restore stateful crawling support

---

openwpm/Extension/firefox/feature.js/index.js
openwpm/Extension/firefox/feature.js/loggingdb.js
openwpm/Extension/webext-instrumentation/src/background/javascript-instrument.ts
openwpm/Extension/webext-instrumentation/src/content/javascript-instrument-content-scope.ts
openwpm/Extension/webext-instrumentation/src/lib/js-instruments.ts
openwpm/config.py
openwpm/js_instrumentation.py
openwpm/task_manager.py
openwpm/utilities/platform_utils.py
test/test_js_instrument_py.py

We now pass along a Dict/JS object for as long as possible, only serialize it to valid JSON and eval at the last reasonable location.
Closes #857

Remove python to js string

---

docs/Platform-Architecture.md
openwpm/browser_manager.py
openwpm/task_manager.py

This piece of code conceptually belongs to the BrowserManagerHandle, so I moved it there.
However I couldn't think of an easy way to remove all references to the TaskManager so for now we still pass the TaskManager as a parameter.

Moved _issue_command to BrowserManagerHandle

---

.gitignore
.readthedocs.yaml
docs/conf.py
docs/environment-rtd.yaml
environment-rtd.yaml
scripts/prune-environment.py

This PR fixes https://github.com/mozilla/OpenWPM/issues/895 by setting up Sphinx to automatically run `sphinx-apidoc` for every build, using the workaround suggested in https://github.com/readthedocs/readthedocs.org/issues/1139#issuecomment-312626491. Also, it moves readthedocs dependencies under `docs/` and makes `prune-environment.py` automatically generate the `environment-rtd.yaml` file whenever we run `repin.sh`, so that we don't have to remember to keep it in sync with the main `environment.yaml` manually.
Note that we have to install all dependencies and not just the ones required to build the docs after all, as `autodoc` [imports the modules](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#module-sphinx.ext.autodoc) in order to extract the docstrings. Not …

Generate module index

---

openwpm/config.py

Our default was to create a literal folder called ~ instead of writing to the homedir

Fixed default data directory, log directory and log file paths

---

openwpm/browser_manager.py

This PR refactors the BrowserManager to be a class inheriting from multiprocess.Process.
This change allows the logic of BrowserManager to be broken up into multiple pieces as indicated by `_start_extension`

Browser manager as class

---

docs/Configuration.md
openwpm/browser_manager.py
openwpm/commands/profile_commands.py
test/test_profile.py

This PR changes [`dump_profile`](https://github.com/mozilla/OpenWPM/blob/dafc26cb562a9d1a7444bb317a12ff69121441a7/openwpm/commands/profile_commands.py#L18L90) so that it saves the whole Firefox profile directory instead of only saving a few of its subcomponents. It also adds a test and expands an existing one in order to test this new feature.
Closes #62.

Save full Firefox profile

---

docs/Configuration.md
openwpm/config.py

Move config documentation into docstrings
issue code - #916

Move config documentation into docstrings

---

.github/workflows/run-tests.yaml
openwpm/commands/profile_commands.py
openwpm/deploy_browsers/deploy_firefox.py
test/test_profile.py

This PR will add more profile tests and eventually close https://github.com/mozilla/OpenWPM/issues/789.
`test_profile_recovery` is a parametrized test that implements the test matrix outlined in https://github.com/mozilla/OpenWPM/issues/789#issuecomment-817924502.
I'll be adding a couple more small tests soon.

Expand profile tests

---

docs/Release-Checklist.md
openwpm/deploy_browsers/configure_firefox.py
openwpm/deploy_browsers/deploy_firefox.py
test/manual_test.py

Hi all! This PR reverts the workaround of manually creating the `user.js` file now that https://github.com/mozilla/geckodriver/issues/1844 has been fixed and the fix has been included in geckodriver v0.30.0.
Closes #867

Revert workaround of manually creating user.js

---

.readthedocs.yaml

Howdy! :wave:
I am @readthedocs-assistant and I am sending you this pull request to upgrade the configuration of your Read the Docs project.
Your project will continue working whether or not you merge it, but I recommended you take it into consideration.
Also, in case you haven't done it already, remember that you can enable the pull request builds for your project to see the effect of these changes. To do it, [follow the instructions](https://docs.readthedocs.io/en/stable/pull-requests.html), close this pull request, and open it again.
_*Note*: This tool is in beta phase. Don't hesitate to ping @astrojuanlu and/or @humitos if you spot any problems._
The following migrators were applied:
- Migrate to `build.tools` configuration.
This uses the new base Docker image based on Ubuntu 20.04 …

Update Read the Docs configuration (automatic)

---

environment.yaml
openwpm/deploy_browsers/selenium_firefox.py

Since `self.log_file` is not used in the constructor, it's okay to let Selenium open the file first, close it and then reopen it ourselves.
This way we don't have to maintain a full clone of the class in our repo, instead only modifying the behaviour we need.

chore(selenium): upgrade to selenium 4.1

---

README.md

**Explain problem:** 
it seems like command from description of OpenWPM was outdated. At leats it will not work with `demo.py` script. 
Old command:
```
mkdir -p docker-volume && docker run -v $PWD/docker-volume:/opt/Desktop \
-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --shm-size=2g \
-it openwpm
```
It mount host machine `$PWD/docker-volume` dir to `/opt/Desktop`  in container, which does not contain `demo.py` execution artifacts (logs, Sqlite db fiels etc.)
**Solution:**
I suggest to change it to 
```
$PWD/docker-volume:/opt/OpenWPM/datadir
```

- update Docker command from `Running Measurements from inside the Container` in README

---

.gitignore
README.md
demo.py
environment.yaml
scripts/environment-unpinned.yaml

This adds the `--tranco` option to the demo script, which will visit the top 5 sites as ranked by that list. I've decided to make it optional as the list may contain NSFW sites and I didn't want that to be the default path. I think they're unlikely to appear in the top 5, but wanted to be safe.
@vringar I'm curious for your thoughts on this. We're adding an additional dependency for an optional demo feature, but IMO a top-sites list is almost certainly needed by most users and folks may not be aware of the Tranco list / not know about the library.

Add optional tranco list to demo script

---

test/test_extension.py
test/test_pages/audio_fingerprinting.html

This is required as AudioContext doesn't work without user interaction

fix(audio_fingerprinting): trigger audio fingerprint with click

---

install.sh

Remove the argument `--force` from `install.sh`.

mamba --force argument removed of  `install.sh` script

---

openwpm/browser_manager.py
openwpm/config.py
openwpm/deploy_browsers/deploy_firefox.py

We are already asserting that the extension socket exists unconditionally here:
https://github.com/openwpm/OpenWPM/blob/5e77c986f1736b937c6603fa8229091d937f50d1/openwpm/browser_manager.py#L750-L760
so noone could have used OpenWPM with the extension disabled

refactor(config): always enable extension

---

docs/Release-Checklist.md
environment.yaml
package-lock.json
scripts/environment-unpinned.yaml
scripts/repin.sh

By using the conda-forge channel exclusively we should get the most up-to-date software
See https://github.com/openwpm/OpenWPM/issues/1111 for the second commit

chore(conda): remove main channel
